### ISSUE TITLE
Whirlpool-gui should ask for the seed passphrase everytime it is connecting to the remote cli

### ISSUE THREAD

**Issue by nickodev** [Samourai-Wallet/whirlpool-gui#16]
I have successfully configured the [whirlpool-cli](https://github.com/Samourai-Wallet/whirlpool-client-cli) and connect to it with the whirlpool-gui. now suppose the below scenario:
- I connect the gui for the first time to the cli and it asks for the seed passphrase
- After the successful connection I can deposit and start the mix
- Then I can close the gui and the mix will continue on the cli server
- When I open the gui later it **doesn't ask** for the seed passphrase and goes strait to the mixing page

Is this intentional?

(GUI 0.9.1, CLIENT-CLI 0.9.1, CLI_API 0.9)

**Comment by zeroleak** [comment]
Hello,
The passphrase is only required to start the CLI.
When the remote CLI is already started, the GUI won't ask for the passphrase again because it's not required. 
When you use the standalone GUI, it always asks for the passphrase at GUI startup because the CLI is killed when you close the GUI.

The passphrase is used to decrypt the seed, but not really intended to protect the GUI, so yes this is the expected behavior.

**Comment by nickodev** [comment]
Hello,
>The passphrase is used to decrypt the seed, but not really intended to protect the GUI, so yes this is the expected behavior.

Thank you for the clear explanation, I should rephrase my question, is there any plan to protect the gui with some kind of a pin number? suppose you setup the gui and forget to delete (reset) it, anyone with access to that machine could open the gui and see what is going on with the mixing and I believe this is not good.

**Comment by pajasevi** [comment]
Hi @nickodev, this is not critical IMO until there would be ability to spend from Whirlpool GUI. I definitely understand your concern but this mainly falls to securing your computer properly which of course you should.

**Comment by nickodev** [comment]
> until there would be ability to spend from Whirlpool GUI

Agreed, got your point.
